ALTER TABLE events ADD COLUMN IF NOT EXISTS recurrence_type VARCHAR(50) DEFAULT 'NONE';
ALTER TABLE events ADD COLUMN IF NOT EXISTS recurrence_end_date TIMESTAMP;
ALTER TABLE events ADD COLUMN IF NOT EXISTS parent_event_id VARCHAR(255);
